[project]
name = "discord-scheduler-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "discord.py>=2.6.3",
    "python-dotenv>=1.0.0",
]